// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvyFKH2CdVzNYEdhKWwfSCTua55nBXRUk',
    appId: '1:941773426611:web:bd730488d51b032b1cc5c6',
    messagingSenderId: '941773426611',
    projectId: 'appfood-5e972',
    authDomain: 'appfood-5e972.firebaseapp.com',
    storageBucket: 'appfood-5e972.firebasestorage.app',
    measurementId: 'G-0ZZB0JP9YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcZPeAa6OEwdTKcmw-q9Wn8C8H93y67qE',
    appId: '1:941773426611:android:e695b7392245c3871cc5c6',
    messagingSenderId: '941773426611',
    projectId: 'appfood-5e972',
    storageBucket: 'appfood-5e972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEkhQMRPGYvzxyAo15UpUrATa3ttrlkJA',
    appId: '1:941773426611:ios:2cdc100635f91fd51cc5c6',
    messagingSenderId: '941773426611',
    projectId: 'appfood-5e972',
    storageBucket: 'appfood-5e972.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEkhQMRPGYvzxyAo15UpUrATa3ttrlkJA',
    appId: '1:941773426611:ios:2cdc100635f91fd51cc5c6',
    messagingSenderId: '941773426611',
    projectId: 'appfood-5e972',
    storageBucket: 'appfood-5e972.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvyFKH2CdVzNYEdhKWwfSCTua55nBXRUk',
    appId: '1:941773426611:web:68bc1166f7c37e971cc5c6',
    messagingSenderId: '941773426611',
    projectId: 'appfood-5e972',
    authDomain: 'appfood-5e972.firebaseapp.com',
    storageBucket: 'appfood-5e972.firebasestorage.app',
    measurementId: 'G-2X5QFHSNJ5',
  );
}
